### ISSUE TITLE
Stream Deck+ support

### ISSUE THREAD

**Issue by florisporro** [Fragtality/PilotsDeck#15]
The new StreamDeck+ has rotary buttons and a separate LCD . The possibilities that brings with it are awesome, from autopilot to comms control. Just wanted to open up an issue to start conversation on support of this new device.

https://www.elgato.com/en/stream-deck-plus

**Comment by Fragtality** [comment]
Don't know when I find Time for that, but support it planed - let's say Q1/2023 😉 

My SD+ has arrived today and it is even worse than I thought it would be ... yes it has Rotaries, but besides it is a "suboptimal" design imho. The primary Reason I bought it is to add to support, not because I like the design 😐

**Comment by florisporro** [comment]
Hmm that's too bad! I would try to help you but my C# is rustier than the Wright Flyer...

**Comment by Fragtality** [comment]
I've obviously not used very long, but I think Quality won't be an Issue!

It is the Design: it has roughly the same Area as the XL, is way taller, costs nearly as much and still it has only 8 Normal Buttons and only 4 Rotaries with all that space available.

**Comment by Zofren** [comment]
It perfectly fits my setup but I see what you mean. A 3x4 buttons grid would have been ideal.

Anyway, Q1 of the Q1 or Q4 of the Q1 ? :)

**Comment by Fragtality** [comment]
Yeah, exactly - that way I would never thought longer than a Second about getting the Plus. With 12 Button is could easily migrate my SD (15-key) Profiles to it, because I'd have enough Buttons for the Num-Keys (GSX, XPDR).

When it's done 😝

**Comment by Cookizza** [comment]
Really excited for this as my + came today. I've got some things setup and got the FCU addon memory scanner running. 

Would it be possible to release an interim version that gives a simple button style control for the rotary knobs? If we can assign to the left/right that would be a start. I understand the LCD integration and options there are probably quite large features and may take some time.

I'll pull the project and see if I can help, although I'm really not hugely familiar with FSUIPC

**Comment by Fragtality** [comment]
> Would it be possible to release an interim version that gives a simple button style control for the rotary knobs? If we can assign to the left/right that would be a start. I understand the LCD integration and options there are probably quite large features and may take some time.

Nope. The LCDs and the Knobs are tied together.

> maybe im ignorant but could the controllers property be added to the manifest to allow the plugins actions to be used for the dials? - https://developer.elgato.com/documentation/stream-deck/sdk/manifest/#actions

Not ignorant, but not familiar enough 😅 
Yeah, that is one of the things which needs to be done. The easiest thing. The Library has to be updated to understand the new Events. I have to create new the Plugin Actions (in the Code) to handle these Events, the Drawing and the Value Handling.
If it would just be adding something to the json, the SD+ Support would have been done by now 😉 

Just leave it to me, I think it is more efficient when I invest my Time in working on the Code than to explain it ^^

**Comment by Fragtality** [comment]
A little bit of Progress-Report 😃 

The Library is extended, the Plugin should now be able to receive the new SD+ Events. Pressing the Dial is already working, since I have routed that Event to the normal KeyDown/KeyUp Event-Handling. The "Display Value with Switch" Action is showing up on the SD+ Encoder. But it still has to be seen if I can maintain the Approach of having the same SD-Action being able to support Keypad and Encoders or if I have to create dedicated Encoder-Only SD-Actions.

Now I to invest some time on the Image Rendering for basic rewrites. Before the SD+ everything was Square with a Resolution of either 72px (SD) or 144px (XL) (respectively the same Scalar which is applied on everything). But now there is a Rectangle and I can not only go after the StreamDeck-Type the Action is on alone - since it can be on a normal Keypad or an Encoder on the SD+.

After that I need to wrap my Head around how to implement the Action Handling. There was only really on Sim-Action / Event per SD-Action so far (the Long Press is only really the same Mechanics) - but now I can have multiple Sim-Actions (Tap, Dial Press, Dial Press Long?!, Dial Rotate) and I of course want to give them the same Degree of Freedom as with the normal Buttons when it comes to supported Action-Types and how they can be adjusted.

Since I also want to have some Benefit for me when investing that much Money & Time, I will be focusing on the Stuff to get FCUs & Co and Radios working on the SD+, since that has the most benefit. But I think we're all on the same Page with that 😅

**Comment by Fragtality** [comment]
I should have a Test-Build for you Guys ready in 1-3 Days 😉 

For now I have enabled 3 Actions for the Dials (aka "Encoders"):
- *Display Value with Switch* (for the FCU Displays for Example)
- *COM Radio*
- *Display Gauge* (only the Single Variant, for ACP Knobs for Example)

Pressing the Dial is mapped to the "normal" ButtonDown / ButtonUp Handling used from the Keypads (so yeah, there is a LongPress Option for the Dial).
The Events for Dial Left / Dial Right / Touch Tap can be mapped to separate/different Actions. All Action Types allowed, but not with all Options (Reset Value for Lvar or Toggle Switch for Controls/XP-Commands for Example).

You may think that the COM Radio should have two Sets of Dial Commands (Outer/Inner Knob) - but that is not really needed thanks to the Encoder-Stack Feature of StreamDeck. Just put two (identical) COM Radio Actions in a Stack and when pressing the Dial the Action is swapped. One Action has the Commands for the Outer Knob, the other for the Inner Knob. Swapping can be done with the Touch Tap Event. That way you can have it all on one Dial (turn > push dial > turn > tap). For easier Identification which Knob/Action is currently selected you can use the Format Option to differentiate the two Actions - for Example I insert a ">" at the Beginning for the Outer Knob and for the Inner Knob a "<" at the End.
<br/>

Using Lvar Actions will now be much easier, reducing the Need to write Lua-Code for them. I still promote using Lua, but for the simple Cases it is not necessary anymore:
- With the Lvar Action, the Variable can now be increased/decreased (with or without a limit) or switched in Sequence.
  - Like "$+1:4" to increase the Variable by 1 with a Limit of 4.
  - Like "$=0,1,2,0" for a Sequence. (The Equal-Sign denotes the Default Value which is used when the next Value could not be found)
- For the Calculator Action, there is now a "Template" to increase or decrease the Lvar without the Need to write the full RPN Code.
  - Like "$E_FCU_SPEED:-1" to decrease the Variable by 1.
  - Like "$A_ASP_VHF_1_VOLUME:-0.1:>=0.1" to decrease the Variable by 0.1 with a Limit of 0.1.

This is especially important for MSFS, since the Lvar or Script Action work, but not are not as smooth when turning the Knob faster - in Contrast to XP-Commands or Controls (more popular under FSX/P3D than MSFS). But manipulating the Lvar via Calculator Code feels really great for the Dials!

**Comment by Cookizza** [comment]
This is amazing, I've been excited all week to hear some progress and it sounds like you've really put some huge effort in the last week or so to produce what you've described.

Really keen to help once there's test builds available - perhaps with profile updates we can all pitch in.

Thanks for the update! Tuned in closely :)

**Comment by Fragtality** [comment]
@Cookizza @Zofren @florisporro 

Here the latest Test-Build, take it for a Spin 😃 
https://github.com/Fragtality/PilotsDeck/raw/master/PilotsDeck-latest.zip

**Comment by Cookizza** [comment]
I've got this rolling and got the FCU all responding.

To confirm - should we now use the exposed LVAR instead of the event number? I'm finding success only with the below (with raw values enabled) on the rotary dials

![image](https://user-images.githubusercontent.com/1787216/212747575-daea4ecc-d07f-4ae3-b30c-452ce9661bff.png)

Also, sorry if it's covered somewhere - but is there a way to format the heading to include a leading zero if under 3 digits?

Thanks so much for this, it's really looking great!

**Comment by Fragtality** [comment]
> To confirm - should we now use the exposed LVAR instead of the event number?

No should from the Plugin side, whatever the Plane needs 😉 
For the Fenix FCU Knobs, you need the E-Variables for turning. (For Knobs with Stop-Position it is A_ and all other Switches are S_)
(And both are Lvars - don't confuse it with event number)
<br/>

> I'm finding success only with the below (with raw values enabled) on the rotary dials using the fenix

What "raw values enabled"? The Plugin does not have something like that.
<br/>

> Also, sorry if it's covered somewhere - but is there a way to format the heading to include a leading zero if under 3 digits?

The "Format" Option just allows a fixed Length after the decimal Point. I'll look into expanding the Format Option - seems really missing when handling numeric Values 🤔 (I personally don't need it, since some kind of external Code does that and I just display the finished String on the Deck)

**Comment by Cookizza** [comment]
Ah sorry - I'm meaning the configuration option from the memory scanner to get the fenix FCU values - https://github.com/Fragtality/PilotsDeck_FNX

With it disabled, the values get formatted nicely but they also get prefixed with HDG, ALT etc which I'm trying to keep off the LCD hence the formatting questions.

**Comment by Fragtality** [comment]
@Cookizza 
Redownload the latest, the Format Option now can apply leading Zeros!

In your Case it would be "3.0" => 3 Signs, no Decimal Part (zero Signs)
The old Syntax of just one Number still works and produces the same Result.

**Comment by Fragtality** [comment]
Oh and also on the Knobs:
You could also manipulate that Lvar via the Calculator Action Type! Just use "$E_FCU_HEADING:-1" (or +1) as the Action Address!

**Comment by kens1108** [comment]
After Version 0.7.5 i can't choose an Action Type (XPCMD or any other)

**Comment by Fragtality** [comment]
Are you running Version 0.7.5 or upgraded from that Version to this Dev-Build? If the latter - seems you have missed the Basics (documented in the Readme): .NET is not on Version 7 or the Binary is blocked by Windows-Security or other AV-Software.

**Comment by kens1108** [comment]
Thanks, 
thats it.... .NET ist not on Version 7...

**Comment by Fragtality** [comment]
Here the next Dev-Build for you all to test :smile:
https://github.com/Fragtality/PilotsDeck/raw/master/PilotsDeck-latest.zip

- The Syntax for the Calculator Template has changed to make it even shorter. Examples:
  - To increase a Lvar by one just write $VARIABLE:1 now
  - If there is a Limit of 4 (not increase beyond that) just write $VARIABLE:1:4 now
  - Floating Point Numbers are allowed of course
- Added an Image Preview in the Property Inspectors
- Fixed a Bug with the new Rounding when also String Replacement was used
- Fixed a Bug where Actions would stop working/displaying because the Variable was unregistered
- Fixed a Bug in the new Lvar Manipulation (Counter / Sequences)
- Fixed some Bugs in the Property Inspectors
- Changed the Binary Packaging to a Self-Contained / Ready-to-Run File
- Lots of rewrites in the Backend
- I've uploaded my current Fenix-Profiles (including the Plus-Profile of course^^)

❕ Please note: Delete everything in the PilotsDeck-Plugin-Folder (except the Sub-Directories) before unpacking the new Version to avoid DLL Conflicts. If you have changed the manifest for Profile Switching with custom Profiles - just use the new ImportProfiles Binary now to update the manifest 😉

**Comment by Fragtality** [comment]
@florisporro  @Zofren  @Cookizza  @kens1108 

Please also try the new Installer: https://github.com/Fragtality/PilotsDeck/raw/master/Install-PilotsDeck-v0.7.8.exe

**Comment by Fragtality** [comment]
Some Changes:
- Added a Template/Shorthand for K-Events on the Calculator Action Typ. Was already possible, if you knew the RPN Syntax :wink: You can Trigger standard or custom Events (like with the FBW) like that:
  - $K:FUELSYSTEM_PUMP_TOGGLE:3
  - $K:A32NX.FCU_SPD_DEC
  - The "K:" is mandatory! (or else it will be interpreted as increase/decrease Code for a Lvar)
  - You don't need to use the FSUIPC Event-Files to use these (regardless of using this Template or direct RPN Code)
  - Prefer this Template when using it on a Encoder, as it will include the "Ticks" send from StreamDeck
- There was a Bug with the Image-Management on the Korry Action (only really showed up when trying to manipulate the Draw-Rectangle)
- The Build-Process now automatically updates the Installer
  - The former Link to the 0.7.8 Installer was removed, to avoid Version-Confusion

https://github.com/Fragtality/PilotsDeck/raw/master/Install-PilotsDeck-latest.exe
https://github.com/Fragtality/PilotsDeck/raw/master/PilotsDeck-latest.zip

**Comment by KR283** [comment]
Moving from 0.7.7 to 0.7.8, custom images (257x257) don't seem to resize on Display Button with Switch

**Comment by Fragtality** [comment]
You mean the Display *Value* with Switch?
On which StreamDeck Type?

The Image Handling was changed since there are now 3 Sizes respectively not everything is square anymore. But it should work as before ... for the correct Size and Naming! The Images can't just have any Size.
Sure the Readme is lacking there, but if you take a look at the included Images, they are 72px with a "hq" Version of 144px (with @2x at the End) used for the XL and Plus.
If you add a hq-Version (@2x) then you need to also add a normal Version.

**Comment by KR283** [comment]
Sorry - yes Display Value with Switch, and using both XL & Plus.

In the image below, both buttons are using the same image at 257px.  Button on the left is Display Value with Switch, and button on the right is a Simple Button.

![image](https://user-images.githubusercontent.com/123463308/214300091-5c94f243-1fca-445e-83e1-7f62f697fef4.png)

This image shows the same 2 buttons, but running on 0.7.7:

![image](https://user-images.githubusercontent.com/123463308/214303235-1ec33cbd-34b0-48b1-9c6f-e68361174a05.png)

**Comment by Fragtality** [comment]
Hmm, interesting 🤔 
And that Picture has no hq-ending right?

**Comment by KR283** [comment]
correct - just tried with the Display Value, and behaviour is the same as Display Value with Switch - also tried appending @2x to the filename with no change

**Comment by Fragtality** [comment]
Again: it has the incorrect Size, regardless of Ending.

The Simple Button (and Dynamic Button) Action just sends the Image to the StreamDeck (which does the Resizing). But all other Actions are rendered - and they assume the default Sizes as defined by Elegato's Style Guide. The Image is rendered centered on the Canvas and the Size of the Canvas is determined by the Deck-Type and Control-Type - not by the Image Size!

**Comment by Fragtality** [comment]
I'm wondering - why that Action at all, when it is about showing an Image and not a Value. Why not the Simple or Dynamic Button?

**Comment by richardkennedy** [comment]
> I'm wondering - why that Action at all, when it is about showing an Image and not a Value. Why not the Simple or Dynamic Button?

Correct me if I'm wrong but a simple button can't manage multiple states and in reality the Dynamic Button and Display Value with State ultimately achieve the same thing? It depends on the use case.

To add my two cents to the above issue - I'm seeing the same problem except, but in my case the images are 256x256. These images were correctly resized with previous plugin versions, are correctly resized by the Streamdeck and other plugins such as Cosmetic. The new behaviour with the Display Value with State seems to be the exception?

**Comment by richardkennedy** [comment]
> You mean the Display _Value_ with Switch? On which StreamDeck Type?
> 
> The Image Handling was changed since there are now 3 Sizes respectively not everything is square anymore. But it should work as before ... for the correct Size and Naming! The Images can't just have any Size. Sure the Readme is lacking there, but if you take a look at the included Images, they are 72px with a "hq" Version of 144px (with `@2x` at the End) used for the XL and Plus. If you add a hq-Version (`@2x`) then you need to also add a normal Version.

The style guide recommendations are to ensure compatibility across various devices but it's not definitely required. Providing the images are proportionate, it does work.

**Comment by Fragtality** [comment]
> Correct me if I'm wrong but a simple button can't manage multiple states and in reality the Dynamic Button and Display Value with State ultimately achieve the same thing? It depends on the use case.

If the Image does not need to change, a Simple Button fits that. Sure, a Dynamic Buttons sounds more likely (differentiation between No Smoke being On or Off). That why I wrote "or". But we both don't know, since we both are not KR283 🤷 
And I can't really grasp you Conclusion, that Dynamic Button and Display Value with Switch would achieve the same Thing?! 😮  The first is Image-based and the latter is Text-based (displaying the Value ...). And only really with the new Image Map Feature they are both comparable, since the Dynamic Button only could display 2-3 different States before.
I'm with you (but only with new Feature) that both fit the Use-Case to manage Multi-State-Switches since both can represent the multiple States. But still it is not "achieve the same thing" because either a User wants to display different Images for that or different Text/Strings as the Representation of the States. Similar, but not same.
And both Display Value Actions are not about displaying Images. And the current example is about displaying an Image. So that it is why I'm asking - why is an Text-Based Action used when it is about Images? 🤔 
<br/>

> To add my two cents to the above issue - I'm seeing the same problem except, but in my case the images are 256x256. These images were correctly resized with previous plugin versions, are correctly resized by the Streamdeck and other plugins such as Cosmetic. The new behaviour with the Display Value with Switch seems to be the exception?

To put that right: the Images *happened to be resized* before. That does not mean it was the correct behavior when using unintended Image-Sizes. It is not an Exception, since all rendered Actions (both Display Value, COM Radio, both Gauges and Korry Button) where and still are tuned to produce either 72 or 144px Images (for Keypads) and assume their Background Image in that respective Size and will show these "no resize" behavior. That they were resized before with these Actions was not intended, so I did not think about unintended Usage when changing the Rendering- and Image-Handling-Code for the SD+ Support.
Since Cosmetic is probably just sending the Image, it works there. But that is exactly what the Simple and Dynamic Button are still doing: they are just sending the Image. And here we are again at the very same Question: When it is about showing an Image as Representation for the State, why is a Text-Based Action used for that?! 🙄 
<br/>

> The style guide recommendations are to ensure compatibility across various devices but it's not definitely required. Providing the images are proportionate, it does work.

Not only compatibility, also to achieve the best visual result. That is why the Images should be provided in distinct Sizes, although it possible when not followed. That is also why Icon Packs follow that (take a look at Guensli's Icons for Example - they are all 144px).
Simply because something *can* or *still* works, does not mean it is always a good Idea to just wave-off *should* Recommendations when a consistent behavior is expected. From IETF RFC2119:
`SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.`

<br/><br/>
Unless I see a sound Reason/Use-Case, I do not consider this as something that needs fixing.
Maybe try to Answer my Question with an Answer. Try to explain the Use-Case so I can understand it. Starting a general Discussion about why it should be correct to ignore Recommendations is not the recommended way to convince me. 😉

**Comment by richardkennedy** [comment]
Is this a difficult issue to correct? The level of detail (you're actually quoting internet standards) seems a bit excessive. I don't need to convince you to resolve the issue, I'm just making you aware (as is the other user) that the recent changes have introduced a regression and I would like to see it resolved. If a new user comes along and creates a dynamic button with a 256x256 image, it'll work as expected. If they create a Display Value /w Switch button, it won't. It's inconsistent and it impacts the user experience.

Dynamic buttons and Display Values with State buttons both support images. Using a display value with switch makes it easier to build and debug a button. The text can then be hidden after the fact.

**Comment by Fragtality** [comment]
It is not really the Question if it is difficult - it is neither Rocket-Science nor is it a simple Code-Change. It is the Question why I should invest time in that? My own private time. For something that would just work if you would either use another (suitable and intended) Action or just Resize the Image. Maybe you should recall that I'm not gaining anything from sharing this Project/Plugin. No, I'm just loosing Time. And even Money - the SD+ was not really something I needed.

And it is not a Regression (which is a Bug) - the Changes did not break a Feature. They did break an unintended behavior which you have kind of "exploited". And well, if you like to see something resolved, especially when I don't consider it as Bug - then you'll either have to convince me or resolve it in your own Fork. It is just as simple as that.

The Argumentation/Example around a new User and an inconsistent Experience/Behavior is true. But the Solution for me is/was to correct the Readme on which Image-Sizes should be used. That is really lacking.

Yeah, the Dynamic Button and the Display Value both support Images. But they use them completely differently! The Dynamic Button is about showing/sending an Image based on the current State/Value. The Display Value Actions are about displaying that State/Value - the Image is just the Background there for the Text. Using a Display Value Action to never Display any Value so it somehow shows Images like the Dynamic Button is just something it was never designed to. It still makes no sense for me to use a Display Value Action when it is not about displaying the Value but an Image instead - there is an Action for that and it still has the same behavior as before.


All I can say is: Your Argumentation is currently having the opposing Effect.

**Comment by Fragtality** [comment]
It was as I feared: allowing non-standard sized Images to correctly resize broke other Stuff and finding out why was difficult due to all the different Handling in the Actions (due to added Features in the past, especially due to SD+ Support). So I rewrote / refactored some Portions of the Code so that there is more common handling in the Code again 😵 

So try the latest Version: https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe
- Non-Standard Size Images now correctly resize on all Actions (also the Korry Sub-Images)
- Drawing-Behavior changed when the Sim is not connected - the Image is rendered like it would be when connected (and configured). So it can be seem what it could look like even when the Sim is not running.
- Pause is now correctly detected for FSX/P3D/MSFS and the Plugin in general reacts to pausing and unpausing faster now
- Some small Fixes I came along but can not remember 😅 

@KR283 @richardkennedy et. al.
The Plugin now makes it easier to just throw in an Image - I'm with you that the Plugin should it not make that different to just use an Image (on all Actions!) and it will just fit. IF the Quality is not important. It is still the recommended way to provide a 72px (none) and a 144px (2x) for optimum Quality (respectively 3x with 200x100 for the Touch-Display).
Should other Problem arise due to non-intended Usage of the Display Value Actions: Please invest your time in describing your Use-Case (Why using that way? What are the Simple/Dynamic Button missing?) and not in Questions of Principle. If there is a sound Reason it is used that way, I'm open to look into possible Solutions/Enhancements.

@florisporro
I'm a little bit "puzzled" that the Poster of Issue shows the least Interest in it? I mean I don't need a full experience report or something like that ... but at least something like a thumbs-up reaction (like Zofren e.g.) on a Post that I know everything is good with the Build respectively the Implementation of the requested Feature.

**Comment by richardkennedy** [comment]
That's great, appreciate your time and effort. I'm in the process of resizing images, and swapping the button types around etc based on the above feedback. Once that's done, I'll move on to testing with the SD+. 

As a side note, are you accepting project donations?

**Comment by Fragtality** [comment]
You don't have to do all Images anymore 😃 
But especially more "iconographic" Images benefit most when being designed/resized to the Standard-Sizes - they look more crisp! For example the Images I provide with the Plugin are not resizes of each other - they where each "drawn" in 72px or 144px.
So a Resize is only really needed if you want two different Sizes for an Image (so that the Plugin selects the right Picture according to Deck-Type) or want to have more control over the Quality (iconographic Images). If that is not imported - just throw it in 😉 

No, I'm not accepting donations. But thanks 👍

**Comment by florisporro** [comment]
> @florisporro I'm a little bit "puzzled" that the Poster of Issue shows the least Interest in it? I mean I don't need a full experience report or something like that ... but at least something like a thumbs-up reaction (like Zofren e.g.) on a Post that I know everything is good with the Build respectively the Implementation of the requested Feature.

@Fragtality Actually, I don't own a StreamDeck+ myself so I haven't been able to try it 🤐

I'm always looking for these type of integrations and when I came accross this project and saw the newly released hardware I thought it might be a good idea, but saw there was no thread for it yet. I just wanted to get the discussion started. Sorry, it was certainly not disinterest on my part, you've been extremely responsive and quick I might add with this update. I might still buy the plus in the future and will certainly try this out then!

**Comment by Fragtality** [comment]
🤣 🤣 🤣

**Comment by richardkennedy** [comment]
@KR283 Have you tested this on your SD+?

**Comment by Fragtality** [comment]
@Zofren @Cookizza @richardkennedy @KR283 @kens1108 
New Test-Build is out! https://github.com/Fragtality/PilotsDeck/raw/master/Install-PilotsDeck-latest.exe

When testing I had again Problems with the L-Var Limit of FSUIPC (3066 max) and since it is unlikely that Asobo or John Dowson can/will fix it in the near Future ... I've introduced Support for MobiFlight's WASM Module! 😅 

- The MF WASM Module is now a Requirement for the Plugin (for MSFS)
  - So for L-Vars there is no Issue with any Limit now! (Unless you own 208 StreamDeck XLs 🤣 )
  - You can now Access A-Vars directly by Name! Examples:
    -  `(A:FUELSYSTEM PUMP SWITCH:2, Bool)`
    -  `(A:LIGHT POTENTIOMETER:13, percent over 100)`
  - This is not a Goodbye to FSUIPC - it is still the Main-Connector for everything but X-Plane. But the Dependency to the FSUIPC WASM Module may be removed in the Future (it is only really used for Calculator Code now which maybe could also replaced with MobiFlight's Module).
- The Installer now checks also the FSUIPC and WASM Versions and Install-State
- The Importer now Remembers the previous Profile-to-Type-Assignments. On subsequent Runs, if there are no added Profiles, it will just add your Profiles to the Manifest without any Input needed.

**Comment by Fragtality** [comment]
Just updated the Build - The Values would not update in some Situations

**Comment by richardkennedy** [comment]
Just checking in to say that I haven't had a chance to test this yet, but I'll provide feedback as soon as possible.

**Comment by Fragtality** [comment]
@Zofren @Cookizza @richardkennedy @KR283 @kens1108
New Test-Build is out! https://github.com/Fragtality/PilotsDeck/raw/master/Install-PilotsDeck-latest.exe

- Dependency from FSUIPC WASM Module completely removed
  - WASM based Variables/Commands should work without changes
  - The Installer still checks the FSUIPC WASM Version but only gives a Notification
- Toggle Switch now available for all Command-Based Action-Types (Macro, Script, H-Var, Calculator, XP-Command)
- Reset Value renamed to Reset Switch. Now available for all Value-Based Action-Types (L-Var, Offset, DataRef, A-Var)
  - It is now also "global" for that Action: When selected it will also be applied to additional Actions like the Long Press, Touch or Dial
- Hold Switch added as new Option for every Action-Type except the vJoys:
  - Similar to a (non-toggle) vJoy Action, the Button will now execute on Key-Down and on Key-Up - like a Joystick button would
  - Handy for Fire-Test, CVR Test, TO Conf or similar Cockpit Controls (does only help when the Control does not reset itself)
  - For Value-Based Action-Types it will send the On Value on Down and the Off Value on Up
  - For Command-Based Action-Types it will send the Action on Down and the Alternate Action on Up
  - Is exclusive to Long-Press (not available when Hold Switch activated)
- Hold & Toggle Switch still only for the "Main Action" (not for Long Press, Touch or Dial-Turn)

**Comment by Fragtality** [comment]
https://github.com/Fragtality/PilotsDeck/raw/master/Install-PilotsDeck-latest.exe

Mainly renaming / reordering Stuff in the Property-Inspector so that there is more commonality and that the Labers are more in line with the new Readme (RM.md for the moment). Getting closer to Release 😉

**Comment by Fragtality** [comment]
Changes included in Release 0.7.8
