### ISSUE TITLE
X-Plane 11 crashes after a while

### ISSUE THREAD

**Issue by Flightport** [Fragtality/PilotsDeck#18]
Hello Fragtality,
as mentioned in my first post, I have problems with crashes of StreamDeck. I use X-Plane 11.55 and it works fine for a while.
Defined some Buttons and Displays for the Toliss A321/A319 and they normally work fine. 
![Toliss_Pilotsdeck](https://user-images.githubusercontent.com/122156042/211212085-c4d63200-6c41-4f90-a0c9-a62ec63e0903.jpg)

Don´t know, what causes this error. The last commands I added were Pitch Trim Down and Up.
[PilotsDeck20230108.log](https://github.com/Fragtality/PilotsDeck/files/10369142/PilotsDeck20230108.log)
Have you got an idea whats going wrong or what I did wrong?
Joerg

**Comment by Fragtality** [comment]
I ask again: you are aware that there is a premade Profile for the ToLiss? Even when you want to structure your own Profile completely differently, you still can copy & paste some Actions from it. Could save you some time maybe 😉 

Please attach the Profile, so that I can test if it is related to the Profile / the Action Settings. (StreamDeck UI -> Manage Profiles -> Right-Click on Profile -> Export)

Which Version are you using?
0.7.6?
0.7.7? ("latest" on the Mainpage, not yet under Releases)

**Comment by Flightport** [comment]
> I ask again: you are aware that there is a premade Profile for the ToLiss? Even when you want to structure your own Profile completely differently, you still can copy & paste some Actions from it. Could save you some time maybe 😉

To be honest, no I did not yet check that, but I will do. Started without knowing, that there is a Toliss Profile allready. I will do that, to be sure you mean this profile? 
https://forums.x-plane.org/index.php?/files/file/83196-pilots-deck-another-streamdeck-plugin/

> 
> Please attach the Profile, so that I can test if it is related to the Profile / the Action Settings. (StreamDeck UI -> Manage Profiles -> Right-Click on Profile -> Export)

I am in the office right now, but will do today evening, you are too fast for me 😉

> Which Version are you using? 0.7.6? 0.7.7? ("latest" on the Mainpage, not yet under Releases)

I think 0.7.6 but will check that in the evening too to be sure.

**Comment by Fragtality** [comment]
>I guess my problem was, that I didn´t modify the manifest file.

The only Time when a User should fiddle with that is for the Profile Switching with own Profiles. Besides that, Users should not touch that File (there is no Need or good Reason).
<br/>

> Only when I open a button for a new config and do not change the copy Action Type from MACRO to XPCMD or XPDRef StreamDeck sometimes hangs. But I can avoid that by changing the value fast enough.

I can't follow you - especially "do not change the copy Action Type from MACRO ..." ?!?
What is a *copy* Action Type? Why would you need to do it fast enough? Unconfigured Buttons can sit there for Ages without harming anything (you can even push them) and you can change the Action Type anytime (after the Dropdown was populated).
<br/>

> I would like to combine your excellent Toliss config with my script but that does not seem to be so easy. The reason is the large number of Datarefs and Commands I already defined in my LUA-scripts. I need them for the Airmanager panels for Overhead, EICAM, Radio and Transponder.

Hmm well, given the Fact you've created your Lua-Scripts already, that should not be a Challenge? You can use the Actions from my Profile and customize them for your custom Datarefs and Commands. I did not want to stop you from building your own Profile/Integration. I just wanted to give a hint, that there is already a Profile which can be used as Example, Inspiration or direct use :wink: 
<br/>

> To be honest, the modification of the manifest file confused me a lot, but that is a Streamdeck-API limitation when I understand you correct.

What exactly confused you there, what could I improve on the Readme?
Yes, it is a Limitation by the StreamDeck Software: Plugins are only allowed to switch to Profiles which the Plugin includes (that's why they have to be added to the manifest).
But: It makes no Sense for your Setup. Profile-Switching for XP11 is not supported. It hasn't got the DataRef for that.

**Comment by Fragtality** [comment]
I too have a fulltime Job and this is just a Hobby (or specifically a private project which consumes Time I could spend with my Hobby) . . .

So is it now still Crashing or not? If yes, please provide a Log from when it happened.

**Comment by Flightport** [comment]
Thanks so much for your time.
I will spend more time when I have the chance and let you know. 
Please close the issue in the meantime, I can open it up again, if I have a crash report with log-file etc.
