### ISSUE TITLE
Can't index LVar

### ISSUE THREAD

**Issue by Adoggman** [Fragtality/PilotsDeck#22]
I'm trying to get the FBW A32NX engines' N1 values, which are stored as LVars `A32NX_ENGINE_N1:{index}` where index is 1 or 2.

Using a Display Value or Display Gauge, I can enter `L:A32NX_ENGINE_N1` as the Variable address but it shows nothing. If I put `L:A32NX_ENGINE_N1:1`, it tells me the input is invalid and does not reflect engine 1's N1 value. This happens whether or not I have the `L:` prefix.

Looking at the documentation, it appears there is a way to index an AVar `(A:Name(:index), Unit)` but no equivalent for an LVar.

**Comment by Fragtality** [comment]
Well, my Motivation to fix Issues which are specific to the A32NX is currently near 0. I may look into this someday, if another Enhancement/Bug Fix requires my Attention.

**Comment by Fragtality** [comment]
Looked into it:
The Reason there is no Equivalent is quite simple: there is no such Thing as an indexed L-Var. Reading out the numerical ID of both "Indices" reveal that these are really two different L-Vars. It is just fancy Names, it could have been also called "_N1_1" and it would be technically the same.

But apparently the colon and also the point are valid Characters for L-Var Names - was not aware of that! (was never an Issue before).
Since I'm interested into improving my Stuff even when I do not experiencing the Issue myself, I'll fixed it in the Dev-Build :)
https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe

**Comment by Fragtality** [comment]
Closed due to no further Feedback
