### ISSUE TITLE
Installer messages

### ISSUE THREAD

**Issue by Samhaho** [Fragtality/PilotsDeck#33]
Hi Fragility,  Just a detail about the installer. Once the installation is terminated a set of messages/report are shown, which is great idea (like everything else in this wonderful software). There is a message about recommending to add NumberOfPumps=0. It would be great just to explicit that this is related to FSUIPC and more specifically to be done in the FSUIPC.ini file.

Cheers,

Sam

**Comment by Fragtality** [comment]
Yeah, I see what you mean ... before that SU12 Issue it was just "All MSFS Requirements met!".
If not met, the specific Software which is missing or not at the right Version is displayed (so it would specifically say FSUIPC or MF WASM) - a User would know in that Case what is meant.

Because of that SU12 Issue I wanted to add some kind of Note to the Installer, so the average User has at least heard something about potential Stutters! (Users who have FSUIPC only installed because Tools like mine told him/her, but does not anything directly with it)
But it is really a bit confusing for anyone but me ... I know that this Box/Check is about FSUIPC (and MF) but for anybody else it is not that clear.

Have to think about it what to do with it.
Maybe just removing it completely because I've picked something up that it might already be set by FSUIPC by Default in the mean time.
Or adding another Check which tests the ini File for that Parameter and only "alerts" when it is not found. Maybe with an Option to let it be automatically fixed by the Installer (a little bit like the link to run the import profile tool automatically).

**Comment by Fragtality** [comment]
Finally added with 0.7.11 😅

**Comment by Samhaho** [comment]
Great. Many thanks.

 

Samer
