### ISSUE TITLE
Heading, Speed, Altitude and NQH variables

### ISSUE THREAD

**Issue by Matthisfr** [Fragtality/PilotsDeck#38]
Hello,

I can't have they variables available for Fenix A320. It is a bug or existing special variables ?
Thanks a lot for this FANTASTIC plugin !!!
Cheers
Stef

**Comment by Fragtality** [comment]
I don't have a Clue what the Issue should be ?!

There are no official Variables (only for the Baro). That is why FenixQuartz is there. The premade Fenix A320 Profiles on flightsim.to include that Tool and have already preconfigured Displays.

**Comment by Matthisfr** [comment]
Thanks for your reply. I've forgot to install the Quartz. But also with it, impossible to have the CPT Baro value.
Do you know why it is so complicated to have they values from Fenix A320 ? it must be easyest to have a simple LVAR ?
Thanks a lot !
Same trouble for the Ks project https://www.kickstarter.com/projects/minicockpit/minifcu-flightsim-autopilot-interface-developed-by-pilots?ref=user_menu

They can't access to they values and Fenix will be just partially supported. Friends and I will move to another A320 if not possible to have what the other A320 gives. :(

**Comment by Fragtality** [comment]
Quartz does not provide the Baro Value because that is not needed, it already provided in the standard SimVar (FSUIPC Offset 0x330 - should be SimVar "KOHLSMAN SETTING MB:index")

But the Value for the StreamDeck Profile is generated in an extra Lua-Script, since displaying it all in one String requires more Logic and more then just reading that Offset/SimVar (could be STD, could be Off, could be inHg).
Seems you have also missed the Part in the Readme on the Lua-Scripts. I'd guess the Buttons for the Landing-Lights are also not working ^^

Well the miniFCU People are either unwilling or incapable.
SimpleFCU just works - because it has open Interface with MobiFlight. That is why an User has generated a Config-File that brings the Values of my Tool to the FCU. Normally you get more Features with paying more Money, not less 🤷‍♂️
