### ISSUE TITLE
Technical Issue - Doesn't work with FSUIPC and Streamdeck

### ISSUE THREAD

**Issue by SaganLo** [Fragtality/PilotsDeck#43]
After MSFS started, all the icons turn to three dots. Nothing changed after the flight is loaded. I've a registered FSUIPC and have downloaded the latest .NET and latest version of both Stream Deck and Pilotsdeck. 

Thanks.

[StreamDeck0.log](https://github.com/Fragtality/PilotsDeck/files/12923822/StreamDeck0.log)

[PilotsDeck20231016.log](https://github.com/Fragtality/PilotsDeck/files/12923804/PilotsDeck20231016.log)

**Comment by Fragtality** [comment]
I'm a bit puzzled by your Log. I don't even understand why the Plugin would go into the Wait-State (the 3 dots) since the StreamDeck Software never send any Event that MSFS is running.

- Did you check the [Troubleshooting-Guidance](https://github.com/Fragtality/PilotsDeck#33---troubleshooting) in the Readme? Maybe it is not initially blocked, but after it is was started by StreamDeck?
- How did you install PilotsDeck? I hope you used the Installer and did not attempt a manual Install? Because you say you have FSUIPC and .NET, but do not mention the Mobiflight Event/WASM Module.

Also, the Images used are a little suspicious to me, since the ones available in the PMDG 737 Profile shared by Ado98 are named completely different. Where is that Profile from?

Please try to reinstall:
- Please remove the Plugin manually
  - Stop the StreamDeck Software
  - Remove the Folder `com.extension.pilotsdeck.sdPlugin` in `Elgato\StreamDeck\Plugins`
- Download the latest installer under [Releases](https://github.com/Fragtality/PilotsDeck/releases) and run it (when I mean "run it" just normal double-click on it. No Command-Line, no Parameters, no "Run as Admin")
- To be sure, make a Reboot of your PC after it has successfully installed
- If the StreamDeck Software does not auto-start with Windows: Start it
- Don't do anything else on the StreamDeck or with the Plugin, just start MSFS (because the Log is a bit hard to read when a user Switches Pages/Folders and triggers Register/Unregister Events of the Plugin-Actions)
- Load into a Flight-Session, does not matter which Aircraft, and hit Ready to Fly
- Give it some Seconds (~10?) and then collect the Logs again

**Comment by SaganLo** [comment]
Hi there,
Yes, it works after I removed Norton Internet Security (simply stop virus
scanning or disabling the firewall won't work).
Thanks
Best Regards,
Edward

**Comment by SaganLo** [comment]
Hi,
I replaced Norton by Bit-defender. Not sure if Norton is too "aggressive"
or else.
Thanks and regards,
Edward
