### ISSUE TITLE
Sim Not Connected

### ISSUE THREAD

**Issue by miket4972** [Fragtality/PilotsDeck#48]
Running Windows 10 with X-Plane 11 and Streamdeck XL with v6.5.0 (19904).  I've created two XPWREF buttons with the sim/operation/failures/rel_seize_0 dataref.  Pressing the button should change the variable to 6 to fail the engine.  When pressing the button, nothing happens.  Log file shows the press but logs a "Sim not connected!"  All is running on the same machine and the config file shows 127.0.0.1 and port 49000.  Attaching the plugin log file and the Streamdeck logfile.

I verified firewall is turned off or anything else that might be blocking the UDP port.

[StreamDeck0.log](https://github.com/Fragtality/Pilo
[PilotsDeck20240128_001.log](https://github.com/Fragtality/PilotsDeck/fi
![Screenshot 2024-01-29 111721](https://github.com/Fragtality/PilotsDeck/assets/158074930/2939adc9-a264-418b-83dc-4d31ffad0db9)
les/14086853/PilotsDeck20240128_001.log)
tsDeck/files/14086847/StreamDeck0.log)

**Comment by Fragtality** [comment]
Don't focus too much on the "Sim not connected" - that is just working as intended. Your Problem is still that the StreamDeck Software does not send an "OnApplicationDidLaunch" Event to the Plugin. Hence it never tries to connect.

Something else is completely off here:
- The Log File has a strange Name, it should never end on _001 or therelike.
- Plugin "crashes" because it was not started by the StreamDeck Software.
- The Plugin is regularly closed and started again.

At the Moment I can just guess: either you have still something which is blocking the Plugin (Anti-Virus?), you're starting the StreamDeck-Software/Plugin/Sim under different Users/Elevations or in another non-normal Way (maybe even leading to multiple Instances of the Plugin).

We could start with the Basics: can you please check how the Binary of your X-Plane Installation is named?
And since you clearly fiddled with the config File: please attach it also.

P.S.: Please look after the Files/Links you attach the next Time - they are split in half which makes it unnecessary complicated to download them 😉

**Comment by miket4972** [comment]
That was it.  The application was named something other than x-plane.exe.  I changed it back and it seems to be working now.  Thank you for the quick response.

**Comment by Fragtality** [comment]
Huh! That is odd. 🤔 

If for whatever Reason the Binary has to have a different Name (always thought "X-Plane.exe" is the Standard for Ages) you can alter the Name in the manifest.json File of the Plugin. It defines (amongst other Things) on which Applications the Plugin wants to receive said Event from the StreamDeck Software. But watch out: The File is overwritten on every Plugin Update.
