### ISSUE TITLE
Noticeable lag with version 0.7.12

### ISSUE THREAD

**Issue by richardkennedy** [Fragtality/PilotsDeck#53]
When compared to version 0.7.10, there's a noticeable lag when moving between pages (buttons show the waiting image for approximately 0.5-1s) on all Stream Deck devices when using version 0.7.12. On video, it appears that the buttons are being drawn left to right, however this could be completely unrelated. Reverting back to version 0.7.10 addresses this issue.

Are you aware of any potential issues?

**Comment by Fragtality** [comment]
Nope, I'm unaware - it is just visual.

**Comment by richardkennedy** [comment]
> Nope, I'm unaware - it is just visual.

It _looks_ like there's a very small delay in it pulling data from FSUIPC, rather than a slow draw, as the wait image appears instantly for that very brief moment. I also think it's more noticeable when changing pages on the SD+ LCD screen, but that might be my perception.

**Comment by Fragtality** [comment]
Well, yes there is a Difference between the Versions:
> Improved: Continuous Input (e.g. turning an Encoder) does not block the Displays being updated

So in order to improve that there where some Changes needed how Events are handled. And an Action appearing is also an Event. The Best I could do without a larger Rewrite.

The Wait Image is not relevant, that is just how it works - it is the static Image defined in the Manifest for every Action, so the StreamDeck Software already loads it (until the Plugin rendered the Image for the Action and send it to the Software).

I don't see any Delays when pulling Data from FSUIPC or Mobiflight - it should even be faster with .12 since the Poll-Time was reduced. I can even see the Fenix FCU flashing on Startup.

**Comment by richardkennedy** [comment]
Appreciate the response and detail. Is there an option to disable this to restore the responsiveness? For example an app.config setting?

**Comment by Fragtality** [comment]
No, such an Option does not exist - the Change was architectural, not a Feature that can be on or off.

**Comment by richardkennedy** [comment]
What's the best route forward? Is this something that you'll be able to look at in the near future or should I remain on 0.7.10? It's a tricky one because the latest Stream Deck libraries from 0.7.12 are required, as without them the rotary dials on the SD+ have a mind of their own.

Thanks as always 👍🏻

**Comment by Fragtality** [comment]
Well, I don't know?

I would not have released .12 if it would severely impair the Usability of the Plugin. I daily-drive it, have no Issues with it and it is the first Time I hear that the changed "visual flow" would be an Issue.

**Comment by richardkennedy** [comment]
Unfortunately it has done ☹️ I've now rolled back to a custom version of 0.7.10 with the updated Stream Deck libs to restore performance.
