### ISSUE TITLE
New feature: guarded switches

### ISSUE THREAD

**Issue by markhlam** [Fragtality/PilotsDeck#54]
Hi,

I think it could be useful to add a new type of item (or at least an additional feature for korrys or dynamic buttons) which are guarded buttons.

I've more or less implemented one using the korry template, assigning the main command to the function I want to operate and the guard control to a long press. Also I assigned both commands to lua scripts acting as follow:
- Long press toggles the guard, and switches off the main function if on
- Short press toggles the function ONLY IF guard is off

In addition to all this I show a message in the top part of the korry when On (same pattern as INOP but with a GUARDED text), and I show ON in the lower part when the main function is activated. However, I couldn't find a way to show OFF when the main function is deactivated either with the guard ON or OFF.

Which I suggest is to natively implement this GUARD mechanism (along with labels for the korrys) even without lua intervention.

GUARDED (there I would like to also show OFF):
![image](https://github.com/Fragtality/PilotsDeck/assets/169832166/f42c07db-8ab0-41cb-b6fd-1cf04f71927d)

UNGUARDED but OFF (there I would like to show OFF)
![image](https://github.com/Fragtality/PilotsDeck/assets/169832166/968d0aff-5534-47be-a054-a6bcc7c82ceb)

UNGUARDED and ON:
![image](https://github.com/Fragtality/PilotsDeck/assets/169832166/9af19149-6160-494c-83c6-7ae7b4b72141)

Thank you!

**Comment by Fragtality** [comment]
Yeah, might be something for the Dynamic and Korry Actions 🤔

**Comment by Fragtality** [comment]
Please test the current Development-Build: https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe
It added a Guarded Switch Options (for the Moment only for Simple, Dynamic and Korry Button) - besides plenty of other Changes (see Commit).

It works differently to what you have described: It draws a Overlay above the current Picture/State, in accordance to the Variable and Value configured to check if the Guard is active. The Guard has a (mostly\*) separate Command: when the Guard is active that Command is triggered. When it is not active, the normal Command is triggered. So if you need to guard a Switch again: use the normal Long-Press Option.

The Overlay can be any Image from the Plugin's Folder, I've also added some Quick&Dirty "Cross" Style Overlays (like in the Airbus Overhead) and a Red Variant of the standard Button Image.
For Dynamic Buttons it can even get "funkier" since you can also use a "Image Map" for the Guard Images, but the "twist" is: these are also compared to the same "main" Variable for the Dynamic Button. That enables Use-Cases like the A320 Fire Push-Buttons - being able to show the "illuminated" State in both guarded and non-guarded State (but still ... you can't display it being pushed).

\* = The Guard Command shares some Behavior of the normal Command, e.g. the Hold, Toggle, Reset Options apply also to the Guard Command. Also it has no separate Monitor Variable for the Toggle Option - it uses the Guard Variable for that.

**Comment by markhlam** [comment]
Tested OK!!!!

It even adds more posibilities to which I suggested. Thenk you very much for attending my request, and specially for attending it so quickly!

**Comment by Fragtality** [comment]
Thanks, great to hear 😃 

You might want to check the latest Build (same Link) - the Guarded Option was added to all remaining Actions (except Display) 😉 (Besides other great new Stuff)

Would be great if you'd look at different Scenarios - I'm not 100% sure yet if all Combinations of Main Commands and Guard Commands work well together and/or can be useful in most-to-all Scenarios (in Terms of Command Types and Options on the Main Command)

**Comment by Fragtality** [comment]
Closed => Added on all (pushable) Actions and Guard Image Mapping allowed on all of these Actions
