### ISSUE TITLE
HondaJet LVAR doesn't meet the format criteria

### ISSUE THREAD

**Issue by richardkennedy** [Fragtality/PilotsDeck#55]
On the HondaJet (HJet) there's a non standard LVAR of 'CPL Pushed' which doesn't meet the LVAR or calculator code format criteria within PilotsDeck. This has been reported directly to the developers, so this is purely an FYI should any changes be possible to work around any similar issues in the future.

HubHop
HA420 AP CPL Button Push
(L:CPL Pushed,bool) ! (>L:CPL Pushed,bool)

https://hubhop.mobiflight.com/preset/?simType=msfs2020&id=e3142ef0-8745-4188-afe5-4d8f4a6cf453

**Comment by Fragtality** [comment]
Oh man, I honestly don't know why Asobo even allows this in the first Place 🤦‍♂️ 

Lvar-Name checking is a bit strict, yes - the Plugin needs to be able to detect if it as an Offset, DataRef, L-Var or A-Var that was entered. BUT: That is for reading Variables. When it comes to the Calculator Action, there is zero checking - it's just passed to the MF Plugin.

**Comment by Fragtality** [comment]
Please test the current Development Build: https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe

It should allow to have a Space Character in L-Var Names. Besides plenty of other Changes (see Commit) it eventually helps with #53

**Comment by richardkennedy** [comment]
Awesome! I'll test this first thing tomorrow and a few of the other editions 😉 (very cool).

**Comment by richardkennedy** [comment]
This seems to work as expected however the command input box displays an exclamation icon that states "Please match the format requested".

Ref #53 - Buttons still draw left to right on the Stream Deck when a page is first opened. Images appear to be cached for a short while as switching between 2 pages re-draws the page quickly until the cache time expires, and then the page redraws from left to right.

.Net version - The installer has switched to downloading the x86 version of .net rather than x64 - not sure if this is intentional but a manual install was required on my system.

**Comment by Fragtality** [comment]
Yeah the Input Checking in the Property Inspector was always more relaxed - because the real & critical Checks happen in the Plugin. But I've changed the Reg Ex for the Property Inspector though - when it does not lead to false-positives with other Read-Types it can stay that way. It's surely is nicer to have this direct Feedback in the Inspector! 😃 

Yeah, I used the wrong Link, corrected 🤦‍♂️ 

The next Commit will have these two Fixes!

On the other Topic: Then it is your Setup or Perception 🤷‍♂️
The Lag was severely reduced and I can't do anything about the Order the StreamDeck Software sends the Messages. And even if I could influence that, there will always be a Order in which the Messages are received (and for the Matter, the Order they are send back) so that whole "oh it does it left to right" Discussion is just a waste of Time.
That the Images are cached should not be something new to you. It is one of the core Principles of the Plugin that it only uses / runs the Ressource for Actions which are currently shown and to release them All (Variables, Images, Scripts) when they are not used anymore by any active Action.

**Comment by richardkennedy** [comment]
> On the other Topic: Then it is your Setup or Perception 🤷‍♂️
> 
> The Lag was severely reduced and I can't do anything about the Order the StreamDeck Software sends the Messages. And even if I could influence that, there will always be a Order in which the Messages are received (and for the Matter, the Order they are send back) so that whole "oh it does it left to right" Discussion is just a waste of Time.
> 
> That the Images are cached should not be something new to you. It is one of the core Principles of the Plugin that it only uses / runs the Ressource for Actions which are currently shown and to release them All (Variables, Images, Scripts) when they are not used anymore by any active Action.

I've rolled back to 0.7.10 again and I can't replicate the same behaviour. I'm testing with 32 buttons per page (dynamic) across 3 pages and it seems very obvious?

**Comment by Fragtality** [comment]
Well, and for me it is obvious that the initial Loading is much faster again with the new Version 🤷‍♂️ 

Therefore I'll go ahead an close this Issue now, since the L-Var Issue is (respectively will be) fixed by the new Version.

You have not given any substantial Information to investigate this, just "Feelings and Perceptions" about Visuals. If you have something to report I can actually work with and investigate in, feel free to post that in the original Issue #53 .
