### ISSUE TITLE
Pilotsdeck Plugin crashing

### ISSUE THREAD

**Issue by NJCNICK** [Fragtality/PilotsDeck#57]
Hi there,

I'm having issues with the plugin crashing and I'm hoping you can help. I've sent you a PM in the FSL forum with all the details but thought I'd mention here in case you haven't seen it.

Thanks in advance

**Comment by Fragtality** [comment]
Going by the Logs you attempt to start it manually? That doesn't work that way.

**Comment by NJCNICK** [comment]
I thought that was what suggested in the troubleshooting section of the read-me using powershell?

I'm not getting any dropdowns or images. I've just been uninstalling/reinstalling the plug-in. I do have Norton AV but I've excluded the plugin and it's never been an issue before.

**Comment by Fragtality** [comment]
Well, yes and no: Yes that is a Suggestion, but the Goal is to identify Cases with Runtime Issues - where the Plugin does not start at all and thus can not create a Log. So there is at least somekind of .NET Runtime. To completely rule out Runtime-Issues, please quote the Output of the Command (run in Console/Powershell): `dotnet --list-runtimes`

Since it can log, please start it as intended (that is by starting the StreamDeck Software) and attach the Log of that Attempt!

You have used the Installer, correct?
If yes: Maybe there are some kind of Permission Errors. Did you used/configured "Run as Admin" on any of the involved Software? (StreamDeck, Plugin, Plugin-Installer). Do not use that for these.

**Comment by Fragtality** [comment]
Haha, now the FSL Forum send me a Notification about your PM 🤣

**Comment by NJCNICK** [comment]
Haha - better late than never!!

So - I have just uninstalled the Norton AV and reinstalled the SD app and the plugin and it's working again!!!

So despite me excluding it all in Norton it was still causing chaos!

Thank you for your time

**Comment by Fragtality** [comment]
Not the first Time I hear that Norton is acting "dumb".
I don't even need an Exceptions with Avast (it is only intercepted once after an Update/Install and afterwards it fine)

**Comment by NJCNICK** [comment]
Well thanks again. I will look at Avast as an option.
