### ISSUE TITLE
 pilotdeck/map enhacement/fpuic7 V

### ISSUE THREAD

**Issue by jmp44** [Fragtality/PilotsDeck#61]
Not easy to wrk with the 3 in same time . If I star directly with msfs , fuipc start and all is good . if I start with map enhacement  : nothing work , if I start manuelly fsupicv7 in same time or before touch are ok but not the little sreens ( like alt ) 
 ,  fsupic start with msfs.bat .
ty for your answer
JMP

**Comment by Fragtality** [comment]
I can't make really Sense of what you have written, so I can only guess.

The Plugin always has required (and for the moment continues to require) FSUIPC7 to be installed and running in order to connect to MSFS. So make sure that FSUIPC is started normally as intended (that is, via the EXE.xml). The Plugin expects that FSUIPC starts during the MSFS Start-Up.
So if you need to do Things differently, you might need to restart the StreamDeck Software (and thus the Plugin) after MSFS has loaded to the Main Menu and (with FSUIPC running & connected!!).
So in Essence, make sure that FSUIPC7 runs and connects normally itself. If it doesn't, you need to contact the Author of it: https://forum.simflight.com/forum/30-fsuipc-support-pete-dowson-modules/

What also can be is that the Way you start Things leads to a Situation where the involved Binaries run under different Users/Elevations. E.g. when running something "As Admin" - that in General causes more Problems that it solves.
