### ISSUE TITLE
Possible LVAR Issue in 0.8.0

### ISSUE THREAD

**Issue by KR283** [Fragtality/PilotsDeck#71]
Hi @Fragtality ,

I've been testing v0.8.0, and for the most part have not had any issues :) 

One I've come across that's not been noted elsewhere is a strange behaviour reading L:A32NX_AUTOPILOT_HEADING_SELECTED.  Screenshot shows an export of the LVARS as seen by FSUIPC, and the output on the streamdeck - I've not seen this behaviour on any other LVARS (yet!)

![image](https://github.com/user-attachments/assets/7f79cebe-ada6-46a7-bf8a-dc3ce15e8cb9)

**Comment by KR283** [comment]
Same button on 0.7.12:
![image](https://github.com/user-attachments/assets/1ff8fcc6-d930-4d96-afd7-d4be2c732e68)

**Comment by Fragtality** [comment]
Great to hear!

I assume that Comparison was made against the same FBW Version? If yes, that is really a good Catch!
I've stumbled across this too when redoing the FBW Profile and thought it was just a Thing they had changed in the mean Time. Sometimes the FBW is a bit "over engineered" so they write some L-Vars with the correct Unit instead of just a Number. When you read that L-Var with the correct Unit of Degrees you get the expected Value: `C:(L:A32NX_AUTOPILOT_HEADING_SELECTED, Degrees)`

But apparently the old Codebase (which I was very focused to get away from xD) did that somehow better respectively in a general Way so that the Value is automatically in the correct Unit. Guess I have to dig through the old Code and have a Look what the Difference is and how I apply it without breaking anything 🤔

**Comment by Fragtality** [comment]
Check out the latest Commit - I reverted the Behavior. Could only do quick Test on P3D on MSFS, but it should now work as before.

**Comment by KR283** [comment]
I'll check now - thanks

**Comment by KR283** [comment]
Now working as expected thanks!

**Comment by KR283** [comment]
One other I've noticed - has the scaling changed on the SD+ LCD?  Previously an oversized image was scaled to fit the LCD, but current behaviour doesn't seem to do this:

![image](https://github.com/user-attachments/assets/3675b1af-ee44-4c12-878c-d09f75dab5a5)
vs
![image](https://github.com/user-attachments/assets/0214140b-b803-42d8-8bcd-3b468a5450ed)

**Comment by Fragtality** [comment]
It is basically a new Plugin - so yes, there were also many Changes to the Rendering of Images. 😅 

Won't do anything about it because:
1) Could have used the correct Image Size & correct Suffixes in the first Place (as was/is recommended)
2) The Draw Rectangle can be configured on all "classic" Actions to tweak an Image
3) The Composite Action allows even more Tweaking of Image Alignment, Size and Position

Especially with the Composite Action, it could be evaluated if an Image is needed at all in that Use-Case - since you could simply define a Text Element for "SPEED"

**Comment by Fragtality** [comment]
Btw - my Profile for the FBW will also be updated (well it is already updated, just waits for everything to be ready for Release) - so you might consider to not put too much work in a FBW Profile. Unless you really really want to build your own Stuff ofc! 😉 

![image](https://github.com/user-attachments/assets/a598c305-c4bc-447d-aa56-643530cbde7b)

**Comment by Fragtality** [comment]
I don't know - this is more a Question what the Simulator allows than what PilotsDeck allows. It just passes the RPN Code as-is to the MF Module which then calls the execute_calculator_code Function with that Code.
