### ISSUE TITLE
Support for any vJoy outside of FSUIPC

### ISSUE THREAD

**Issue by rkantos** [Fragtality/PilotsDeck#8]
Currently it seems vJoy support with FSUIPC needs registered version (as seems to do lua scripts too). I am currently using this instead: https://github.com/ashupp/Streamdeck-vJoy 

Seem to be GPL license, so not directly compatible with this project though.

**Comment by Fragtality** [comment]
Could you specify the issue / feature request more exactly?
The whole Plugin is built around FSUIPC - what could be a reason to support anything outside of FSUIPC?

Maybe the Readme is a bit misleading? The "vJoy" Action has nothing to do with ashupp's SD-Plugin or the vJoy Device-Driver.
This Action uses Offsets 29F0/3340 for the "Virtual Buttons" which are provided by FSUIPC (therefore the Readme says "as documented in FSUIPC"). 
As far as I'm informed, the free Version of FSUIPC should allow access to Controls and Offsets - so the Virtual Buttons (vJoy Action) could work since it only uses Offsets. But maybe that also belongs to the "Joystick control facilities" of a registered Version.
LUA Scripts/Actions are indeed only possible with the registered Version.

What do you want to express with the "License compatibility issue"?! It's two complete different pieces of software with different purposes not related to each other - so what is the issue with having different Licensing?
Maybe you suggest some kind of integration? In my opinion this is not needed, because:
a) they are both StreamDeck-Plugins, one can mix & match their Actions on the StreamDeck. Meaning both can be used simultaneously if really needed.
b) on of the reason to develop StreamDeck was to have an Alternative to the vJoy-Plugin, to have a Plugin that can communicate bi-directional and can therefore enable "live" / "interactive" Buttons which represent their current State.

So the only ToDo's I understood so far:
- Research if the Virtual Buttons (of FSUIPC) are useable in the free Version
- Add a Description in the Readme what is supported with the free Version of FSUIPC (and a Recommendation to have a registered Version)
- Clarified Description of what is meant with the "vJoy Action" (e.g. that is not related to the vJoy SD Plugin / Device-Driver)

**Comment by rkantos** [comment]
You are almost correct in how the problem is understood. 

Basically there are two cases which are true, either you have paid FSUIPC - which means this is not a problem at all.

In the other case (without having paid FSUIPC) you can of course use other plugins without issues. However - if it was possible to use unregistered FSUIPC and "standalone vJoy" with Pilotsdeck buttons - then you wouldn't have to use additional space for the 2nd plugin's button, of the button which would consume one spot on the Streamdeck. As you know with your plugin it is possible to have at least three different functions in one button (display, press, long press). With using an other plugin you could thereby possibly using at least 2x the pages in streamdeck if one button could only do one thing because the standalone vJoy plugin cannot show values like Pilotsdeck.

You are still right about the license, because I was thinking about some sort of integration with it.

Also, most of the time you can of course use alternative methods - especially now since you added support for single function indicating JeeHell-like bitmask FSUIPC-offsets. 

Without either or it wouldn't have been possible to implement the same kind of one page (on the 15btn Streamdeck.) FCU as I have done with the LevelD767 on FSX by using Pilotsdeck with FSUIPC user offset values which are translated by SIOC and in to SIOC by Leekseecon, which is the only way to display some LevelD767 values without using their C-SDK directly. (Lekseecon<->SIOC<->FSUIPC IN/OUT user offsets 64 bytes<->Pilotsdeck)

Again, with paid FSUIPC - there is no issue at all - except maybe in the very special case (which could happen in theory still) of implementing more than the FSUIPC limit of vJoy offsets.

**Comment by Fragtality** [comment]
I would close this Issue then, since the Readme now points out what Action Types do not work with a free Version and that a registered Version is recommended.

I do respect, that one does not want to spend the money for FSUIPC.
But please understand that I won't invest my private time to save other people money.
It is not the intended target audience for this Plugin.
