### ISSUE TITLE
Font scaling

### ISSUE THREAD

**Issue by richardkennedy** [Fragtality/PilotsDeck#86]
Have any changes been made to font scaling in 0.8.X? Sizes appear to be linked to Windows Scaling settings which they weren't previously.

Edit: Yes. PD buttons now behave completely differently to other plugins and standard Elgato buttons. 

What's the reason for this?

**Comment by Fragtality** [comment]
Who can possibly know
![image](https://github.com/user-attachments/assets/57b12150-09a6-4e08-bfb4-5d7673e7a23d)

**Comment by Fragtality** [comment]
Follow these Instructions closely:
(Or let it be, I'm already testing that with People having an actual interest in proper Troubleshooting)

- Ensure your Windows Display Settings are the same as when you created your Profile / Actions
- Create an empty Profile on all your StreamDeck(s).
- Copy at least one Classic Action (anything not a Composite Action) containing Text and at least one Composite Action containing Text to this empty Profile(s).
Actions *you* have created in *your* Setup. Do not modify them - copy them as they are.
And with Text I mean Text rendered by the Plugin - so no Buttons with just a StreamDeck Title displayed on it.
- **Ensure such an empty Profile is set as the current Profile on all your StreamDeck(s)**
- **Do not run a Sim during the Test**. If you do, ensure that you have Profile-Switching disabled.
- Install this Version: https://www.mediafire.com/file/17avi48rdxuvwq9/Install-PilotsDeck-latest.exe/file
- **Do not switch Profiles on any Deck!**
- *Please answer*: How do the (copied) Actions look (in Terms of Font-Size)? Maybe they slightly changed in Size* but are they about the same - not overly small or large? (* = visually, the actual Font-Size in the Settings will be different!)
Put differently: how do they looked to you, if and what difference did you notice?
- Export that empty Profile, with the copied Actions (regardless of the Answer to the previous Questions) and attach it here (change the Extension as needed, doesn't hurt).
- Optional: if you still have a pre-0.8.0 Profile lying around, import that to the StreamDeck Software (it is okay to switch to that Profile then). Same Questions apply, but do not export.
- **Install the Release Version (0.8.5) again!** https://github.com/Fragtality/PilotsDeck/releases/download/v0.8.5/Install-PilotsDeck-v0.8.5.exe
- Done, all good again. (Yes, the copied Actions from the Test will look different then.)

**Comment by Fragtality** [comment]
FYI, the Changes where now pushed as normal Development-Build
https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe

**Comment by KR283** [comment]
I've done some testing against the Development-Build, and noted a peculiarity with the way a font is scaled when either first loaded on the new version or imported - the font size is multiplied by whatever the screen scaling is currently set to 

For example, a Display Value with a font size of 10 on a profile exported with screen scaling set to 100%, then imported with screen scaling set to 150% will change to having a font size of 15.

I believe it’s exceptionally important that the original behaviour is restored. The current method isn’t practical, requires more effort to correct previous profiles and takes control away from the user and the profile author by automatically modifying font sizes

**Comment by Fragtality** [comment]
> I believe it’s exceptionally important that the original behaviour is restored. 

And what do you think is the Change about? 😉

**Comment by Fragtality** [comment]
> I've done some testing against the Development-Build, and noted a peculiarity with the way a font is scaled when either first loaded on the new version or imported - the font size is multiplied by whatever the screen scaling is currently set to

That is intentional and required. There is no Information on what DPI an Action was created.
So Profiles need to be fixed on the Creator Side so that their current DPI is used for Conversion (which was used at Design-Time, leading to the intended Size on the StreamDeck).
To convert the Actions to a new Size looking the same for everyone.

<br/>

> The current method isn’t practical, requires more effort to correct previous profiles and takes control away from the user and the profile author by automatically modifying font sizes

When the Creator has converted the Profile (so basically upgrading the Plugin and opening all Folder/Pages), it can already be publish as an Update. With the updated Profile looking the same for every of its Users (without any Intervention).

What the User controls is "how big" the Text should be on the StreamDeck. That hasn't gone away. The Conversion is done to keep it "this big". And "this big" is important, the Value of X is not.

So I can only absolutely disagree.

The Arguments are also contradicting - so keeping that imaginary Control would mean not doing any Conversion. That leads actually to everyone having much more Efforts because the Actions are now "visually broken" (but untouched - yay?).

**Comment by Fragtality** [comment]
Fixed in 0.8.6
