### ISSUE TITLE
Display value with Switch button shows 0 value even when "Hide value" is selected

### ISSUE THREAD

**Issue by rkantos** [Fragtality/PilotsDeck#9]
Issue occurs as per title. Doesn't seem to happen with "Dynamic button", in which you can determine two values.

**Comment by Fragtality** [comment]
Could you describe the Bug / Issue more precisely?
The "Display Value (with Button)" Action displays the Value directly, the "Dynamic Button" represents the Value (respectively the Button's States) as different Images. Of course it does not "seem to happen" there, because the Value is never (directly) displayed.

Also I can't reproduce the Issue - when I e.g. configure a Display Value (with Button) Action and enable "Hide Value" for Special Value of "0" (or any other) it is hidden.
Maybe it is a misunderstanding? The "Hide Value" only refers to the configured "Special Value" (like 2000 for Squawk, 1013/29.92 for Baro) and will only hide the Value when they are equal (to e.g. use a different Background Image for that). If unequal, the current Value is shown. An Action which purpose it is to display a Value wouldn't make much sense if it never displays a Value ;)

Should you need the reverse case, that anything but the Special Value is hidden, I'd like to know more on the Use-Case. That could be replicated with a Dynamic Button which uses the "Empty" Image as Background and for one State/Value a custom Image with the desired Value. It's a bit clumsy, but it would be a workaround.

**Comment by rkantos** [comment]
Thanks for the great reply. I have recognized that you can use the  Dynamic Button. however with the dynamic button I cannot use the basic control (e.g. single press) functionality like I can with "Display value with Switch". Currently I am using for example in the LevelD 767 MCP the "Display value with Switch".

With the Display value with Switch button my LevelD767 MCP looks like this when for example SPD mode is not enabled:
![image](https://user-images.githubusercontent.com/16664350/115153890-cf5a6d00-a080-11eb-8205-987e19d995dc.png)

![image](https://user-images.githubusercontent.com/16664350/115153772-48a59000-a080-11eb-918a-0873606b20c3.png)

I have both short press and long press enabled when using this functionality, which cannot be done with the Dynamic button because it is not possible to monitor one value, use Control for controlling other value which then affects the monitored value and Second Control for a third value. With Dynamic Button I can only control two values and the Control value needs to be the display value too. ( see https://github.com/Fragtality/PilotsDeck/issues/6 )

With my LevelD767 MCP I have the following for HDG button for example:
Read Value: Offset $66E6 (FSUIPC OUT in SIOC, O_HDGHLDLed in Lekseecon)
Single press: Offset $66C9 (FSUIPC IN in SIOC, HDG mode in Lekseecon)
Long press: Offset $66C8 (FSUIPC IN in SIOC, HDG Hold in Lekseecon)

Another example with SPD mode which works pretty much the same way except Long Press is used for Speed Intervention.
If I wanted to display the Speed Intervention in the same button I could only display it if the button could be configured with 2nd read value and something like O_SPDINTLed. In the 767 Speed Intervention is displayed by the SPD value becoming visible while in VNAV. Thus currently I would have to have a 2nd read value for the "Display Value with Switch", since the blanking of the SPD display is done by a third variable in Lekseecon. This would be another feature request also, but it is not such critical, albeit my VNAV button doesn't fit on the 15 button Streamdeck. 

Actually, writing the above made me realize that maybe the Display Value with Switch could have a further Action type for Control / Second Control in the form of opening a folder or a different profile. Then I could replace my single folder button for the VNAV button above the LNAV button.

The same is only possible in Dynamic button by using the long press functionality with Control Status value of Offset $66E6 but the single press is not possible since the status of HDGHLDLed is at a different offset. The $66C9 offset only toggles between 0/1 as input and it's value isn't changed by SIOC/Lekseecon - it is only intrepreted by them as input. Therefore you loose the control of one value.

**Comment by Fragtality** [comment]
I've got what I asked for, that it is bit too detailed xD

So basically, you do need different Control Status and Action Addresses or more specific that they have different Values for On/Off?
But wouldn't that be somehow resolvable when you would use Lua-Script instead, because they not need a Value for On/Off? I'm not a Boeing-Guy, but I could fit my A320 FCU with no Problems on the "Normal" 15-key Deck in two Folders via LuaToggle Actions.

An Action-Type to open a Folder or Profile won't happen. There are StreamDeck Actions for Folders and Profile-Switching already builtin (on-top on the already included Feature that the Plugin can switch Profiles based on FSUIPC Profile). I do organize my Actions/Bindings completely with Folders and do not see a use case to reinvent the wheel?

**Comment by Fragtality** [comment]
CLOSED - implemented

Control Status and Action Address can now be different!
